server {
    listen 8080; # http://localhost:8080
    server_name localhost; # nom de domaine accepte
    root /sgoinfre/goinfre/Perso/nmartin/Nicelife/; # repertoire racine du site
    #index index.html;
    #autoindex off; # si ON, serveur génère une page HTML automatiquement qui liste le contenu du dossier
    # si OFF serveur ne liste pas le dossier, si index.html existe il s'en sert sinon 403/404
    #client_max_body_size 10M; # taille maximale d'une requete
    #error_page 404 /errors/404.html;
    #error_page 500 /errors/500.html;
    
    # Fichiers statiques
    #location / {
        #allowed_methods GET POST; 
    #}
    
    # Upload de fichiers
    #location /upload {
        #allowed_methods POST;
    #    upload_enable on;
    #    upload_store ./pathtouploads; # fichiers envoyes seront enregistres dans ce dossier
    #    autoindex off;
    #}
    
    # CGI déclenché par extension (.py, .php, .sh)
    #location /cgi { # execution scripts cgi
    #    #allowed_methods GET POST;
    #    autoindex off;
    #}
}